src/main/java/cdi/named/LogadoBean.java

package cdi.named;

import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named("usuario")
@RequestScoped
public class LogadoBean implements Serializable {
    @Inject
    private LoginBean login;

    public LogadoBean() {
    }
    
    public String getNome() {
        return login.getLogin();
    }
}

src/main/java/cdi/named/LoginBean.java
package cdi.named;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class LoginBean implements Serializable {
    private String login;
    private String senha;

    public LoginBean() {
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    public String loginAction() {
        return "confirma";
    }
}

src/main/webapp/WEB-INF/templates/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <f:view>
        <ui:insert name="metadata"/>
        <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <link href="./css/default.css" rel="stylesheet" type="text/css" />
            <link href="./css/layout.css" rel="stylesheet" type="text/css" />
            <title>IF6AE - Exemplo CDI</title>
            <ui:insert name="styles"/>
            <ui:insert name="javascript"/>
        </h:head>

        <h:body>
            <table class="table_layout">
                <tr>
                    <td class="left_filler"/>
                    <td id="top">
                        <ui:insert name="top">
                            <a href="http://www.ct.utfpr.edu.br" target="_blank"><img src="imagens/header.jpg" alt=""/></a>
                        </ui:insert>
                    </td>
                    <td class="right_filler"/>
                </tr>
                <tr>
                    <td class="left_filler"/>
                    <td id="content">
                        <ui:insert name="content">Content</ui:insert>
                    </td>
                    <td class="right_filler"/>
                </tr>
                <tr id="bottom">
                    <td class="left_filler"/>
                    <td>
                        <ui:insert name="bottom">
                            <div class="bottom_content">
                            </div>
                        </ui:insert>
                    </td>
                    <td class="right_filler"/>
                </tr>
            </table>
        </h:body>
    </f:view>
</html>

src/main/webapp/confirma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="./WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="./css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h:panelGroup>
                <h:outputText value="#{usuario.nome}"/> logado!
            </h:panelGroup>
            
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                template="./WEB-INF/templates/layout.xhtml">

    <ui:define name="metadata"/>
    <ui:define name="styles"/>
    <ui:define name="javascript"/>

    <ui:define name="content">
        <h:form>
            <h:panelGroup layout="block" styleClass="">
                <h:outputLabel for="usuario" value="Usuário:"/>
                <h:inputText id="usuario" value="#{loginBean.login}"/>
            </h:panelGroup>
            <h:panelGroup layout="block" styleClass="">
                <h:outputLabel for="senha" value="Senha:"/>
                <h:inputSecret id="senha" value="#{loginBean.senha}"/>
            </h:panelGroup>
            <h:commandButton value="Entrar" action="#{loginBean.loginAction}"/>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>